### ISSUE TITLE
Compile IPF file

### ISSUE THREAD

**Issue by zckrs** [fiote/treeofsavior-addons#1]
Hi,  how do you pack/compile IPF file for game after extract/decrypt?

**Comment by fiote** [comment]
Hi Zckrs! Well, my addons doesn't change any IPFs, so i'm not the most experienced guy to talk about it. That said, i'm pretty sure the same program you use to decrypt (and I used IPFUnpacker-master) can encrypt the files again. After that you just need to replace the file on your /data folder. That's not advised, though. You're effectively hacking the client when you do that (even if you mean no harm).  

Since the mapviewer addon changes IPF files (I guess?), maybe you can get a better answer with Exclulon (https://github.com/Excrulon/Tree-of-Savior-Lua-Mods).

Hope that clears you doubt a little!
