### ISSUE TITLE
Slash-Commands conflicting with LKChat

### ISSUE THREAD

**Issue by GosuSan** [fiote/treeofsavior-addons#18]
When [LKChat](https://github.com/Lemon-King/ToS-LKChat) is installed, your /cw + /farmed + /comp - Commands do not work at all. I know they provide an API for slash-commands, so I guess there is a conflict somewhere. When I remove LKChat from my addons, everything works fine. Both, your Suite and LKChat are on the newest version. If you need any more info, just let me know.  
PS: Great work with your Addons!

**Comment by HilltribeG** [comment]
Are you using Normal Chat to enter your commands? I have LKChat + Excrulon + cwAPI running right now just fine.

**Comment by YamashitaRen** [comment]
Same here.

**Comment by fiote** [comment]
@GosuSan / @YamashitaRen , i'm not really looking into this. Since most of players got it working, it's clearly something wrong if your setup. STILL, somewhat in the future all my addons will be moving to a UI-options instead of slash commands, so no more conflicts should emerge. Closing this for now :)
